<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head>

<!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Easy HR Comms - Samples</title>
	<meta name="description" content="Employee communictions and internal employee communication graphic design samples">  
	<meta name="author" content="Easy HR Comms">
	<meta name="keywords" content="Human Resources, Open Enrollment Communications, Benefit Guide, Health and Wellness Newletter, Animated Power Point, Microsite, Email Header, Employee Communications, Employee Health and Wellness ">
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->


    <script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "ImageObject",
      "contentUrl": "https://easyhrcomms.com/samples/images/2023-campaign/sample-campaign-hero-2500.webp",
      "creditText": "Easy HR Comms Open Enrollment",
      "creator": {
        "@type": "Person",
        "name": "Jackson Taylor"
       },
      "copyrightNotice": "Jackson Taylor"
    }
	
	
	    {
      "@context": "https://schema.org/",
      "@type": "ImageObject",
      "contentUrl": "https://easyhrcomms.com/samples/index.php#wellness-nesletters.php",
      "creditText": "Easy HR Comms Newsletters",
      "creator": {
        "@type": "Person",
        "name": "Jackson Taylor"
       },
      "copyrightNotice": "Jackson Taylor"
    }
    </script>
	
	

<!-- Head Global
   =================================================== --> 

   <?php include("../head.php"); ?>

  <!-- Head This Page
   =================================================== -->  
	<link rel="stylesheet" href="/photoswipe/dist/photoswipe.css">
	<link rel="stylesheet" href="css/styles-portfolio.css"><!-- in portfolio folder css folder-->

   <style>

.grid-container {
  display: grid;
  grid-template-columns: auto auto auto auto;
  background-color: #fff;
  padding: 5px;

}
.grid-item {
  background-color: rgba(255, 255, 255, 0.8);
  border: 0px solid rgba(0, 0, 0, 0.8);
  padding: 5px;
  font-size: 30px;
  text-align: center;

}

.grid-item img {

height: 100%;
width: 100%;
object-fit: cover;
}

.item-1 {
  grid-area: 1 / 1 / 3 / 3;
}



</style>
</head>

    <!-- BODY
    ================================================== -->
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WL9DPFX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="comms-pro"></div>

	    <!-- CALVIN preloader
    ================================================== -->
    <div id="preloader"> 
    	<div id="loader"></div>
    </div>

<!-- Header
   =================================================== -->
<?php include("includes/header-portfolio.php"); ?>


   <!-- Page Title
   ================================================== -->
    <section id="page-title" >	 	  
		<div class="row">	 	  
		 <?php include("includes/samples-title-menu.php"); ?> 
</div>		 
   </section> <!-- /page-title -->
   
<section id="sample-page-samples">


<!--GALLERY 1 Test WepP-->
      <div class="row" >

<div id="samples-wrapper" class="bgrid-fourth s-bgrid-third mob-bgrid-half group" data-aos="fade-up">

<?php include("galleries/gallery-vanilla-grid.php"); ?>
<?php include("galleries/gallery-avif-grid.php"); ?>

</div>
</div>

<!--END GALLERY 1-->




</section>

<!-- contact
   =================================================== -->
<?php include("../contact.php"); ?>  

<!-- journal
   =================================================== -->
<?php include("../footer.php"); ?> 

   
<!--CALVIN ss-go-top
<div class="ss-go-top">
	<a class="smoothscroll" title="Back to Top" href="#top">
		<svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
			<path d="M7.5 1.5l.354-.354L7.5.793l-.354.353.354.354zm-.354.354l4 4 .708-.708-4-4-.708.708zm0-.708l-4 4 .708.708 4-4-.708-.708zM7 1.5V14h1V1.5H7z" fill="currentColor"/>
		</svg>
	</a>
</div>
end ss-go-top -->
	
 <!-- Calvin Java Script
   ================================================== -->
    <script src="/js/jquery-3.5.0.min.js"></script>
    <script src="/js/plugins.js"></script>

   <!-- PureMedia Java Script
   ================================================== -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> 
   <script src="/js/waypoints.js"></script>  
   <script src="/js/main.js"></script>

   

<script>
var jq16 = jQuery.noConflict(true); 

(function ($) {
    $(document).ready(function () {
        console.log($.fn.jquery); // Output: "1.6.2"
    });
})(jq16);

console.log($.fn.jquery); // Output: "3.5.0"

</script> 


<!--PHOTO SWIPE AVIF CAPTION. -->

<script type="module">
import PhotoSwipeLightbox from '../photoswipe/dist/photoswipe-lightbox.esm.js';
const lightbox = new PhotoSwipeLightbox({
  gallery: '#gallery--avif',
  children: 'a',
  pswpModule: () => import('../photoswipe/dist/photoswipe.esm.js')
});

// Parse data-pswp-webp-src attribute
lightbox.addFilter('itemData', (itemData, index) => {
  const webpSrc = itemData.element.dataset.pswpWebpSrc;
  if (webpSrc) {
    itemData.webpSrc = webpSrc;
  }
  return itemData;
});

// use <picture> instead of <img>
lightbox.on('contentLoad', (e) => {
    const { content, isLazy } = e;

    if (content.data.webpSrc) {
      // prevent to stop the default behavior
      e.preventDefault();

      content.pictureElement = document.createElement('picture');
      
      const sourceWebp = document.createElement('source');
      sourceWebp.srcset = content.data.webpSrc;
      sourceWebp.type = 'image/avif';

      const sourceJpg = document.createElement('source');
      sourceJpg.srcset = content.data.src;
      sourceJpg.type = 'image/jpeg';

      content.element = document.createElement('img');
      content.element.src = content.data.src;
      content.element.setAttribute('alt', '');
      content.element.className = 'pswp__img';

      content.pictureElement.appendChild(sourceWebp);
      content.pictureElement.appendChild(sourceJpg);
      content.pictureElement.appendChild(content.element);

      content.state = 'loading';

      if (content.element.complete) {
        content.onLoaded();
      } else {
        content.element.onload = () => {
          content.onLoaded();
        };

        content.element.onerror = () => {
          content.onError();
        };
      }
    }
});


// by default PhotoSwipe appends <img>,
// but we want to append <picture>
lightbox.on('contentAppend', (e) => {
  const { content } = e;
  if (content.pictureElement && !content.pictureElement.parentNode) {
    e.preventDefault();
    content.slide.container.appendChild(content.pictureElement);
  }
});

// for next/prev navigation with <picture>
// by default PhotoSwipe removes <img>,
// but we want to remove <picture>
lightbox.on('contentRemove', (e) => {
  const { content } = e;
  if (content.pictureElement && content.pictureElement.parentNode) {
    e.preventDefault();
    content.pictureElement.remove();
  }
});

lightbox.on('uiRegister', function() {
  lightbox.pswp.ui.registerElement({
    name: 'custom-caption',
    order: 9,
    isButton: false,
    appendTo: 'root',
    html: 'Caption text',
    onInit: (el, pswp) => {
      lightbox.pswp.on('change', () => {
        const currSlideElement = lightbox.pswp.currSlide.data.element;
        let captionHTML = '';
        if (currSlideElement) {
          const hiddenCaption = currSlideElement.querySelector('.hidden-caption-content');
          if (hiddenCaption) {
            // get caption from element with class hidden-caption-content
            captionHTML = hiddenCaption.innerHTML;
          } else {
            // get caption from alt attribute
            captionHTML = currSlideElement.querySelector('img').getAttribute('alt');
          }
        }
        el.innerHTML = captionHTML || '';
      });
    }
  });
});
lightbox.init();
</script>


  
<!--PHOTO SWIPE CAPTION VANILLA -->
<script type="module">import PhotoSwipeLightbox from '../photoswipe/dist/photoswipe-lightbox.esm.js';
const options = {
  gallery:'#gallery--captions',
  children:'a',
  pswpModule: () => import('../photoswipe/dist/photoswipe.esm.js')
};

const lightbox = new PhotoSwipeLightbox(options);
lightbox.on('uiRegister', function() {
  lightbox.pswp.ui.registerElement({
    name: 'custom-caption',
    order: 9,
    isButton: false,
    appendTo: 'root',
    html: 'Caption text',
    onInit: (el, pswp) => {
      lightbox.pswp.on('change', () => {
        const currSlideElement = lightbox.pswp.currSlide.data.element;
        let captionHTML = '';
        if (currSlideElement) {
          const hiddenCaption = currSlideElement.querySelector('.hidden-caption-content');
          if (hiddenCaption) {
            // get caption from element with class hidden-caption-content
            captionHTML = hiddenCaption.innerHTML;
          } else {
            // get caption from alt attribute
            captionHTML = currSlideElement.querySelector('img').getAttribute('alt');
          }
        }
        el.innerHTML = captionHTML || '';
      });
    }
  });
});
lightbox.init();
</script>



  

</body>

</html>